language: node_js
node_js:
  - stable
before_deploy: rm -rf .git .travis.yml
deploy:
  - provider: s3
    access_key_id: ${AWS_ACCESS_KEY}
    secret_access_key: ${AWS_SECRET_KEY}
    bucket: "libelluswebapp"
    skip_cleanup: true
